export const WORKS = [
  {
    slug: "aura-beauty",
    title: "Aura Beauty",
    type: "3D Web Experience",
    role: "Frontend Engineer & Designer",
    year: "2026",
    pipeline: "Figma → Next.js + R3F + GSAP → Vercel",
    problem:
      "Static product photos can't convey a cosmetic product's texture, formulation, or feel online.",
    desc: "Immersive scrollytelling showcase for a premium cosmetics brand — a scroll-synced WebGL product that rotates and morphs through the story, with custom frosted-glass shader materials, cursor-tracking physics, and real-time shade tinting at 60 FPS.",
    tagline: "Scroll-synced WebGL storytelling for a premium cosmetics brand.",
    tags: ["Next.js", "TypeScript", "React Three Fiber", "GSAP", "Tailwind CSS"],
    github: "https://github.com/trxshx14/aura-beauty",
    demo: "https://aura-beauty-omega.vercel.app/",
  },
  {
    slug: "attendme",
    title: "AttendMe",
    type: "Full-Stack App",
    role: "Full-Stack Developer",
    year: "2026",
    pipeline: "Figma → React + Spring Boot → Render",
    problem:
      "Manual attendance tracking is error-prone and time-consuming for instructors.",
    desc: "Attendance management system with REST API architecture and role-based access control for school admins and teachers — secure authentication, real-time recording, and a clean dashboard.",
    tagline: "Role-based attendance management, from REST API to dashboard.",
    tags: ["React", "Spring Boot", "MySQL", "Android"],
    image: "/images/attendme-dashboard.png",
    github: "https://github.com/trxshx14/IT342-Cararag-AttendMe",
    demo: "https://attendme-frontend.onrender.com/login",
    apk: "/AttendMe.apk",
    caseStudy: "/attendme-case-study",
  },
  {
    slug: "cozy-pomodoro",
    title: "Cozy Pomodoro",
    type: "Frontend App",
    role: "Frontend Developer & Designer",
    year: "2025",
    pipeline: "Figma → React + Tailwind → Vercel",
    problem:
      "Students and professionals struggle with distraction and burnout during long study or work sessions.",
    desc: "Productivity-focused Pomodoro timer with a soft, lofi-inspired interface designed for focused work and mindful breaks.",
    tagline: "A calm, lofi-inspired Pomodoro timer for focused work.",
    tags: ["React", "Tailwind CSS"],
    image: "/images/cozy-dashboard.png",
    github: "https://github.com/trxshx14/CozyPomodoro",
    demo: "https://cozypomodoro-by-trishadev.vercel.app/",
    caseStudy: "/cozy-pomodoro-case-study",
  },
  {
  slug: "nook",
  type: "3D Product Design",
  year: "2026",
  role: "Solo build — concept, 3D interaction design, engineering",
  title: "Nook",
  image: "/images/nook-cover.png", // swap in your own screenshot
  problem:
    "3D spatial manipulation is naturally clunky for a casual user — dragging objects in a scene, avoiding the camera fighting back, snapping things into place without pixel-perfect fiddling. Most browser-based 3D tools feel like engineering demos, not products.",
  desc:
    "A cozy 3D room arranger: pick from pastel furniture pieces across 6 categories, drag them into a room that snaps to a grid, rotate and recolor them, then re-skin the whole space with one-click aesthetic themes — Cozy Cottage, Retro 70s, Space Minimalist. A resident pathfinding cat wanders the floor and sits down in protest if your furniture blocks her path. One Zustand store is the single source of truth — the same placedItems array drives the 3D scene, the UI panels, persistence, and the cat's pathing logic.",
  pipeline: "Concept → UX flow → R3F prototype → interaction polish → deploy",
  tags: ["React 18", "TypeScript", "React Three Fiber", "drei", "Zustand", "Vite"],
  demo: "https://nook-trc.vercel.app/",
  github: "https://github.com/trxshx14/Nook",
},
];